[vcs]
enabled = false
client_kind = "git"
use_ignore_file = false

[files]
ignore = []

[db]
host = "127.0.0.1"
port = 54322
username = "postgres"
password = "postgres"
database = "postgres"

[linter]
enabled = true

[linter.rules]
recommended = true

[linter.rules.safety.banDropColumn]
level = "warn"
options = { test = "HELLO" }


