[package]
authors.workspace    = true
categories.workspace = true
description          = "<DESCRIPTION>"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "pglt_text_size"
repository.workspace = true
version              = "0.0.0"

[dependencies]
schemars = { workspace = true, optional = true }
serde    = { workspace = true, optional = true }

[features]
schema = ["dep:schemars"]
serde  = ["dep:serde"]

[dev-dependencies]
serde_test        = "1.0"
static_assertions = "1.1"

[[test]]
name              = "serde"
path              = "tests/serde.rs"
required-features = ["serde"]
