[package]
authors.workspace    = true
categories.workspace = true
description          = "<DESCRIPTION>"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "pgt_lexer"
repository.workspace = true
version              = "0.0.0"


[dependencies]
regex = "1.9.1"

pg_query.workspace          = true
pgt_diagnostics.workspace   = true
pgt_lexer_codegen.workspace = true

pgt_text_size.workspace = true

[dev-dependencies]
insta.workspace = true

[lib]
doctest = false
