[package]
authors.workspace    = true
categories.workspace = true
description          = "<DESCRIPTION>"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "pg_schema_cache"
repository.workspace = true
version              = "0.0.0"


[dependencies]
anyhow.workspace = true
async-std            = { version = "1.12.0" }
futures-util = "0.3.31"
serde.workspace      = true
serde_json.workspace = true
pg_diagnostics.workspace = true
pg_console.workspace = true
sqlx.workspace = true

[dev-dependencies]
pg_test_utils.workspace = true

[lib]
doctest = false
