[package]
name = "parser"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cstree = { version = "0.12.0", features = ["derive"] }
pg_query = "0.7"
logos = "0.13.0"
serde_json = "1.0"
regex = "1.9.1"
serde = { version = "1.0", features = ["derive"] }

sourcegen.workspace = true
pg_query_proto_parser.workspace = true
