[package]
authors.workspace    = true
categories.workspace = true
description          = "<DESCRIPTION>"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "pg_statement_splitter"
repository.workspace = true
version              = "0.0.0"


[dependencies]
pg_lexer.workspace  = true
text-size.workspace = true

[dev-dependencies]
ntest    = "0.9.3"
pg_query = "0.8"
