
[package]
authors.workspace    = true
categories.workspace = true
description          = "<DESCRIPTION>"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "pglt_analyser"
repository.workspace = true
version              = "0.0.0"

[dependencies]
pglt_analyse   = { workspace = true }
pglt_console   = { workspace = true }
pglt_query_ext = { workspace = true }
serde          = { workspace = true }

[dev-dependencies]
pglt_diagnostics = { workspace = true }
termcolor        = { workspace = true }
pglt_test_macros ={ workspace = true }
insta = { version =  "1.42.1"}