[package]
authors.workspace    = true
categories.workspace = true
description          = "<DESCRIPTION>"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "pg_typecheck"
repository.workspace = true
version              = "0.0.0"


[dependencies]
insta                     = "1.31.0"
pg_console.workspace      = true
pg_diagnostics.workspace  = true
pg_query_ext.workspace    = true
pg_schema_cache.workspace = true
sqlx.workspace            = true
text-size.workspace       = true
tokio.workspace           = true
tree-sitter.workspace     = true
tree_sitter_sql.workspace = true

[dev-dependencies]
pg_test_utils.workspace = true
unicode-normalization   = "0.1.24"

[lib]
doctest = false

[features]
