[package]
name = "postgres_lsp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.9.0"
tokio = { version = "1.17.0", features = ["full"] }
tower-lsp = { version = "0.19.0", features = ["proposed"]}
dashmap = "5.1.0"
ropey = "1.5.0"
serde_json = "1.0.78"
serde = { version = "1.0", features = ["derive"] }
log = "0.4.18"
