[package]
description = "Internal script to make sure that the metadata or the rules are correct"
edition     = "2021"
name        = "rules_check"
publish     = false
version     = "0.0.0"

[dependencies]
anyhow                 = { workspace = true }
pgt_analyse            = { workspace = true }
pgt_analyser           = { workspace = true }
pgt_console            = { workspace = true }
pgt_diagnostics        = { workspace = true }
pgt_query_ext          = { workspace = true }
pgt_statement_splitter = { workspace = true }
pgt_workspace          = { workspace = true }
pulldown-cmark         = "0.12.2"
