[package]
description = "Internal script to make sure that the metadata or the rules are correct"
edition     = "2021"
name        = "rules_check"
publish     = false
version     = "0.0.0"

[dependencies]
anyhow                = { workspace = true }
pg_analyse            = { workspace = true }
pg_analyser           = { workspace = true }
pg_console            = { workspace = true }
pg_diagnostics        = { workspace = true }
pg_query_ext          = { workspace = true }
pg_statement_splitter = { workspace = true }
pg_workspace_new      = { workspace = true }
pulldown-cmark        = "0.12.2"
