[package]
authors.workspace    = true
categories.workspace = true
description          = "<DESCRIPTION>"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "pg_workspace"
repository.workspace = true
version              = "0.0.0"


[dependencies]
biome_deserialize         = "0.6.0"
dashmap                   = "5.5.3"
futures                   = "0.3.31"
ignore                    = { workspace = true }
pg_analyse                = { workspace = true, features = ["serde"] }
pg_analyser               = { workspace = true }
pg_completions            = { workspace = true }
pg_configuration          = { workspace = true }
pg_console                = { workspace = true }
pg_diagnostics            = { workspace = true }
pg_fs                     = { workspace = true, features = ["serde"] }
pg_query_ext              = { workspace = true }
pg_schema_cache           = { workspace = true }
pg_statement_splitter     = { workspace = true }
pg_typecheck              = { workspace = true }
rustc-hash                = { workspace = true }
serde                     = { workspace = true, features = ["derive"] }
serde_json                = { workspace = true, features = ["raw_value"] }
sqlx.workspace            = true
text-size.workspace       = true
tokio                     = { workspace = true, features = ["rt", "rt-multi-thread"] }
toml                      = { workspace = true }
tracing                   = { workspace = true, features = ["attributes", "log"] }
tree-sitter.workspace     = true
tree_sitter_sql.workspace = true

[dev-dependencies]

[lib]
doctest = false

[features]
