[package]
authors.workspace    = true
categories.workspace = true
description          = "<DESCRIPTION>"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "pgt_diagnostics_categories"
repository.workspace = true
version              = "0.0.0"


[dependencies]
schemars = { workspace = true, optional = true }
serde    = { workspace = true, optional = true }

[features]
schema = ["dep:schemars"]
serde  = ["dep:serde"]

[build-dependencies]
quote = "1.0.14"
