[package]
authors.workspace    = true
categories.workspace = true
description          = "<DESCRIPTION>"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "pgt_fs"
repository.workspace = true
version              = "0.0.0"


[dependencies]
crossbeam       = { workspace = true }
directories     = "5.0.1"
enumflags2      = { workspace = true }
parking_lot     = { version = "0.12.3", features = ["arc_lock"] }
pgt_diagnostics = { workspace = true }
rayon           = { workspace = true }
rustc-hash      = { workspace = true }
schemars        = { workspace = true, optional = true }
serde           = { workspace = true, optional = true }
smallvec        = { workspace = true }
tracing         = { workspace = true }

[features]
schema = ["dep:schemars", "pgt_diagnostics/schema"]
serde  = ["dep:serde"]

[lib]
doctest = false
