[package]
authors.workspace    = true
categories.workspace = true
description          = "<DESCRIPTION>"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "pgt_markup"
repository.workspace = true
version              = "0.0.0"


[dependencies]
proc-macro-error = { version = "1.0.4", default-features = false }
proc-macro2      = { workspace = true }
quote            = "1.0.14"

[dev-dependencies]

[lib]
proc-macro = true
