[package]
authors.workspace    = true
categories.workspace = true
description          = "<DESCRIPTION>"
edition.workspace    = true
homepage.workspace   = true
keywords.workspace   = true
license.workspace    = true
name                 = "pglt_lexer"
repository.workspace = true
version              = "0.0.0"


[dependencies]
regex = "1.9.1"

pg_query.workspace           = true
pglt_diagnostics.workspace   = true
pglt_lexer_codegen.workspace = true

text-size.workspace = true

[dev-dependencies]
insta.workspace = true

[lib]
doctest = false
